import "./globals.css";
import { Outfit } from "next/font/google";

// local imports
import HeadBar from "@/components/HeadBar";
import Footer from "@/components/Footer";
import RecoilWrapper from "@/components/RecoilWrapper";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Amayama Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilWrapper>
          <HeadBar />
          {children}
          <Footer />
        </RecoilWrapper>
      </body>
    </html>
  );
}
